name: Deploy Prefect flow

on:
  push:
    branches:
      - main
    paths:
      - 'leasing/src/flows/**'
      - '.github/workflows/prefect-cd.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: make prefect-deploy
        
  notify-failure:
    needs: deploy
    if: failure()
    uses: ./.github/workflows/slack-notify-failure.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}